# FlexPod reference architecture post-deployment heat template
# - Adds Pacemaker resource records for NetApp E-Series 
#   filesystem mounts that persist across system reboots.
# - Disables Nova DiskFilter as it is completely broken with NFS-backed storage
#   See https://bugzilla.redhat.com/show_bug.cgi?id=1302074 for more info.
# - Unlike pre-deployment environment files, this environment file 
#   is all-encompassing.
#
# Copyright 2016 NetApp, Inc.
#  
# Contributors:
# Dave Cain, Original Author
# 

heat_template_version: 2014-10-16
description: Extra Post-Deployment Config for nodes after the core Puppet configuration

parameters:
  servers:
    description: ID of the node to apply this config to
    type: json
  SwiftNetappEseriesLuns:
    type: string

resources:
  NetAppEseriesPacemakerMountsConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: |
            #!/bin/bash
            # Pacemaker resource mounts to have NetApp E-Series LUNS mounted by Pacemaker
            ESERIESLUNS=(_ESERIESLUNS_)
            #only execute on the first node in the pacemaker cluster
            if [ `hostname -s` == "overcloud-controller-0" ]; then
              for i in "${!ESERIESLUNS[@]}"
                do
                  echo ${ESERIESLUNS[$i]}
                  pcs resource create swift-eserieslun${ESERIESLUNS[$i]}-fs Filesystem params device="/dev/eserieslun${ESERIESLUNS[$i]}" directory="/srv/node/eserieslun${ESERIESLUNS[$i]}" fstype="xfs" "options=_netdev,nobarrier,noatime,nodiratime,inode64" force_clones="yes" --clone interleave=true
                done
            fi
          params:
            _ESERIESLUNS_: {get_param: SwiftNetappEseriesLuns}

  NovaDiskFilterDisableConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        # Disable the broken DiskFilter in nova.conf
        # See https://bugzilla.redhat.com/show_bug.cgi?id=1302074
        openstack-config --set /etc/nova/nova.conf DEFAULT scheduler_default_filters RetryFilter,AvailabilityZoneFilter,RamFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter

  NetAppEseriesPacemakerMountsDeployments:
    type: OS::Heat::SoftwareDeployments
    properties:
      name: NetAppEseriesPacemakerMountsDeployments
      servers: {get_param: servers}
      config: {get_resource: NetAppEseriesPacemakerMountsConfig}
      actions: ['CREATE'] # Only do this on CREATE

  NovaDiskFilterDisableDeployments:
    type: OS::Heat::SoftwareDeployments
    properties:
      name: NovaDiskFilterDisableDeployments
      servers: {get_param: servers}
      config: {get_resource: NovaDiskFilterDisableConfig}
      actions: ['CREATE'] # Only do this on CREATE
